### ISSUE TITLE
Disconnect() on NoOp client

### ISSUE THREAD

**Issue by h-marvin** [marpaia/graphite-golang#23]
Proposing to fix the `Disconnect()` call for the NoOp client:

https://github.com/marpaia/graphite-golang/pull/22/files

Would be great if you could add these lines. Thanks in advance.

**Comment by marpaia** [comment]
Can you open the PR please? It's closed right now.

**Comment by h-marvin** [comment]
Sorry, but it is a bit complicated with open-source contributions in my company 😞. I would appreciate if you could just copy + paste the lines in the file.

**Comment by marpaia** [comment]
Sorry, I'm not super comfortable doing that.
